# example config (~/.config/wlgrid/config.toml)
mode = "grid"   # "fuzzel" or "grid"
alpha = 0.08 # only for fuzzel mode, this is forgetting factor 
width = 6
height = 6
opacity = 1
icon_size = 42.0
custom_entries = []
# asdf
[bottom_bar]
font = 30
options = """
󰍃 = hyprshutdown
󰑓 = systemctl reboot
󰐥 = systemctl poweroff
󰒲 = systemctl hibernate
󰤄 = systemctl suspend
"""

